apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: weeklyreview
spec:
  # Run every Sunday 8am
  schedule: "0 8 * * Sun"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: list2card
            image: bessenyeicsilla/trello-list2card:0.1.2
            volumeMounts:
            - name: credentials
              mountPath: "/src/etc"
              readOnly: true
          volumes:
          - name: credentials
            secret:
              secretName: test
