apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: weeklyreview
spec:
  schedule: "0 0 9 * 6"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: list2card
            image: bessenyeicsilla/trello-list2card
            volumeMounts:
            - name: credentials
              mountPath: "/src/etc"
              readOnly: true
          volumes:
          - name: credentials
            secret:
              secretName: test
