apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: weeklyreview
spec:
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: docker-registry-dockerconfigjson
